# version: "3.0"

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: non
      device: /home/lsadiq/data/wordpress
      o: bind
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: non
      device: /home/lsadiq/data/mariadb
      o: bind

services:
  mariadb:
    build: ./requirements/mariadb
    pull_policy: never
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "3306:3306"

  nginx:
    build: ./requirements/nginx
    pull_policy: never
    image: nginx
    container_name: nginx
    volumes:
    - wordpress:/var/www/wordpress
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    pull_policy: never
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    build: ./requirements/wordpress
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
  monitor:
    container_name: monitorix
    build: ./requirements/bonus/monitorix
    env_file:
      - .env
    image: monitorix
    restart: unless-stopped
    networks:
      - inception
    ports:
      - 8080:8080
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis
    restart: always
    networks:
      - inception
    ports:
      - "6379:6379"